#define GRAIL_PP_PRAGMA(x) _Pragma(#x)
#define GRAIL_PP_REVIVE(m) GRAIL_PP_PRAGMA(push_macro(#m))GRAIL_PP_PRAGMA(pop_macro(#m))

#define GRAIL_PP_PSTR(x...) #x
#define GRAIL_PP_STR(x...) GRAIL_PP_PSTR(x)

#define GRAIL_PP_EAT(...)
#define GRAIL_PP_SCAN(x...) GRAIL_PP_REVIVE(GRAIL_PP_SCAN) x
#define GRAIL_PP_EMPTY

#define GRAIL_PP_TUPLE_AT_0(P,a,...) P##a
#define GRAIL_PP_TUPLE_AT_2(P,a,b,c,...) P##c

#define GRAIL_PP_IF_(P,t,f...) GRAIL_PP_REVIVE (GRAIL_PP_IF_) P##f
#define GRAIL_PP_IF_0(P,t,f...) GRAIL_PP_REVIVE (GRAIL_PP_IF_0) P##f 
#define GRAIL_PP_IF_1(P,t,...) GRAIL_PP_REVIVE (GRAIL_PP_IF_1) P##t
#define GRAIL_PP_NIF_(P,t,f...) GRAIL_PP_REVIVE (GRAIL_PP_IF_) P##f
#define GRAIL_PP_NIF_0(P,t,f...) GRAIL_PP_REVIVE (GRAIL_PP_IF_0) P##t
#define GRAIL_PP_NIF_1(P,t,...) GRAIL_PP_REVIVE (GRAIL_PP_IF_1) P##t

#define GRAIL_PP_IS_NIL_TEST(x...) ,##x

#define GRAIL_PP_IS_NIL(P,x) GRAIL_PP_SCAN(GRAIL_PP_TUPLE_AT_2 GRAIL_PP_EAT() (GRAIL_PP_IF_,GRAIL_PP_IS_NIL_TEST(x),0,1))

#define GRAIL_PP_0VARG_IS_EMPTY(P...) \
GRAIL_PP_SCAN(GRAIL_PP_TUPLE_AT_0 GRAIL_PP_EMPTY (GRAIL_PP_IF_,,##P 1))

#define GRAIL_PP_0VARG_ISNT_EMPTY(P...) \
GRAIL_PP_SCAN(GRAIL_PP_TUPLE_AT_0 GRAIL_PP_EMPTY (GRAIL_PP_IF_,,##P 0))

#define GRAIL_PP_LEFT(P,x...) GRAIL_PP_REVIVE(GRAIL_PP_LEFT) P##x

#define GRAIL_PP_SEQ_HEAD(P,s) GRAIL_PP_SCAN(GRAIL_PP_TUPLE_AT_0 GRAIL_PP_EMPTY (,GRAIL_PP_X_COMMA P##s))
#define GRAIL_PP_X_COMMA(x...) GRAIL_PP_LEFT(,##x),


#define GRAIL_PP_SEQ_FOREACH(P,f,s) GRAIL_PP_0VARG_IS_EMPTY(s) (GRAIL_PP_SEQ_FOREACH_,STOP,LOOP) (,P##f,P##s)

#define GRAIL_PP_SEQ_FOREACH_LOOP(P,f,s) \
GRAIL_PP_REVIVE(GRAIL_PP_SEQ_FOREACH) \
GRAIL_PP_REVIVE(GRAIL_PP_SEQ_FOREACH_LOOP) \
P##f (GRAIL_PP_SEQ_HEAD (,s)) \
GRAIL_PP_SCAN(GRAIL_PP_SEQ_FOREACH GRAIL_PP_EMPTY (,f,GRAIL_PP_EAT s))

#define GRAIL_PP_SEQ_FOREACH_STOP(P,f,_) GRAIL_PP_REVIVE(GRAIL_PP_SEQ_FOREACH_STOP)


#define GRAIL_PP_FOLD_ARGS(f, x, args...) GRAIL_PP_0VARG_IS_EMPTY(args) (GRAIL_PP_FOLD_ARGS_,STOP,LOOP) (f,x,args)

#define GRAIL_PP_FOLD_ARGS_LOOP(f,x,args...) \
GRAIL_PP_REVIVE (GRAIL_PP_FOLD_ARGS) \
GRAIL_PP_REVIVE (GRAIL_PP_FOLD_ARGS_LOOP) \
f (GRAIL_PP_FOLD_ARGS (f,args),x)

#define GRAIL_PP_FOLD_ARGS_STOP(f,x,...) GRAIL_PP_REVIVE (GRAIL_PP_FOLD_ARGS_STOP) x


#define GRAIL_PP_MAP_ARGS(f,x,args...) \
GRAIL_PP_REVIVE(GRAIL_PP_MAP_ARGS) \
GRAIL_PP_0VARG_IS_EMPTY(args) (GRAIL_PP_MAP_ARGS_,STOP,LOOP) (f,x,args)

#define GRAIL_PP_MAP_ARGS_LOOP(f,x,args...) \
GRAIL_PP_REVIVE(GRAIL_PP_MAP_ARGS_LOOP) \
f (x),GRAIL_PP_MAP_ARGS(f,args)

#define GRAIL_PP_MAP_ARGS_STOP(f,x,...) \
GRAIL_PP_REVIVE(GRAIL_PP_MAP_ARGS_STOP) \
f(x)


#define GRAIL_PP_UNTIL(p,s,o,x...) p (x) (GRAIL_PP_UNTIL_,STOP,LOOP) (p,s,o,x)

#define GRAIL_PP_UNTIL_LOOP(p,s,o,x...) \
GRAIL_PP_REVIVE (GRAIL_PP_UNTIL) \
GRAIL_PP_REVIVE (GRAIL_PP_UNTIL_LOOP) \
o (x) \
GRAIL_PP_SCAN (GRAIL_PP_UNTIL GRAIL_PP_EMPTY (p,s,o, s (x)))

#define GRAIL_PP_UNTIL_STOP(p,s,o,x...) GRAIL_PP_REVIVE(GRAIL_PP_UNTIL_STOP) x

#define GRAIL_PP_SELECT(a,b) GRAIL_PP_REVIVE(GRAIL_PP_SELECT) GRAIL_PP_SELECT_##a##_##b
#define GRAIL_PP_SELECT_1_1(P,tt,tf,ft,ff) GRAIL_PP_REVIVE(GRAIL_PP_SELECT_1_1) P##tt
#define GRAIL_PP_SELECT_1_(P,tt,tf,ft,ff) GRAIL_PP_REVIVE(GRAIL_PP_SELECT_1_) P##tf
#define GRAIL_PP_SELECT__1(P,tt,tf,ft,ff) GRAIL_PP_REVIVE(GRAIL_PP_SELECT__1) P##ft
#define GRAIL_PP_SELECT__(P,tt,tf,ft,ff) GRAIL_PP_REVIVE(GRAIL_PP_SELECT__) P##ff


#define GRAIL_PP_0IS_1(x...) \
GRAIL_PP_REVIVE(GRAIL_PP_0IS_1) \
GRAIL_PP_SCAN (GRAIL_PP_0VARG_IS_EMPTY (x) (,GRAIL_PP_IF_,GRAIL_PP_0VARG_IS_EMPTY GRAIL_PP_0DEC (x)))


#define GRAIL_PP_0EQ(a,b) \
GRAIL_PP_REVIVE(GRAIL_PP_0EQ) \
GRAIL_PP_SCAN (GRAIL_PP_SELECT GRAIL_PP_EMPTY (GRAIL_PP_0VARG_IS_EMPTY a (,1,), GRAIL_PP_0VARG_IS_EMPTY b (,1,))) \
(GRAIL_PP_,IF_1,IF_,IF_,0EQ (GRAIL_PP_0DEC a, GRAIL_PP_0DEC b))


#define GRAIL_PP_0INC(x...) (,x)
#define GRAIL_PP_0DEC(P,x...) (x)


#define GRAIL_PP_0PLUS(a,b) \
GRAIL_PP_REVIVE(GRAIL_PP_0PLUS) \
GRAIL_PP_SCAN (GRAIL_PP_0VARG_IS_EMPTY a (,b,GRAIL_PP_0PLUS (GRAIL_PP_0DEC a, GRAIL_PP_0INC b)))


#define GRAIL_PP_0TIMES(a,b) \
GRAIL_PP_REVIVE(GRAIL_PP_0TIMES) \
GRAIL_PP_0VARG_IS_EMPTY a (,() GRAIL_PP_EAT,GRAIL_PP_0VARG_IS_EMPTY b) (,(),GRAIL_PP_0TIMES_A (a,b,()))

#define GRAIL_PP_0TIMES_A(a,b,r) \
GRAIL_PP_REVIVE(GRAIL_PP_0TIMES_A) \
GRAIL_PP_0VARG_IS_EMPTY a (,r,GRAIL_PP_0TIMES_A (GRAIL_PP_0DEC a, b, GRAIL_PP_0PLUS (r,b)))


#define GRAIL_PP_0MINUS(a,b) \
GRAIL_PP_REVIVE(GRAIL_PP_0MINUS) \
GRAIL_PP_0VARG_IS_EMPTY a (,b,GRAIL_PP_0MINUS (GRAIL_PP_0DEC a, GRAIL_PP_0DEC b))


#define GRAIL_PP_0REPEAT(x,n) \
GRAIL_PP_REVIVE(GRAIL_PP_0REPEAT) \
(GRAIL_PP_SCAN(GRAIL_PP_LEFT GRAIL_PP_0REPEAT_I (x,n,())))

#define GRAIL_PP_0REPEAT_I(x,n,r) \
GRAIL_PP_REVIVE(GRAIL_PP_0REPEAT_I) \
GRAIL_PP_0VARG_IS_EMPTY n(,r,GRAIL_PP_0REPEAT_I(x,GRAIL_PP_0DEC n,(GRAIL_PP_SCAN r,x)))


#define GRAIL_PP_0ZIP(l,r) \
GRAIL_PP_REVIVE(GRAIL_PP_0ZIP) \


#define GRAIL_PP_VARG_AT_0(a,...) a
#define GRAIL_PP_VARG_AT_1(a,b,...) b
#define GRAIL_PP_VARG_AT_2(a,b,c,...) c
#define GRAIL_PP_VARG_AT_3(a,b,c,d,...) d


#define GRAIL_PP_0TO_LIT(x) \
(GRAIL_PP_0TO_LIT_I(x) 0)

#define GRAIL_PP_0TO_LIT_I(x) \
GRAIL_PP_REVIVE(GRAIL_PP_0TO_LIT_I) \
GRAIL_PP_0VARG_IS_EMPTY x(,,-~GRAIL_PP_0TO_LIT_I(GRAIL_PP_0DEC x))

